[package]
name = "INCIDENT"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
figleter = "0.2.2"
rand = "0.9.0"
rascii_art = "0.4.5"
rodio = "0.21.1"
strip-ansi-escapes = "0.2.1"
terminal_size = "0.4.3"
whoami = "2.1.1"
